output "user_pool_id" {
  description = "Cognito user pool ID."
  value       = aws_cognito_user_pool.this.id
}

output "user_pool_arn" {
  description = "Cognito user pool ARN."
  value       = aws_cognito_user_pool.this.arn
}

output "user_pool_client_id" {
  description = "App client ID."
  value       = aws_cognito_user_pool_client.this.id
}

output "user_pool_client_secret" {
  description = "App client secret (generated by Cognito; stored in Secrets Manager, never emitted as a plan/CI output)."
  value       = aws_cognito_user_pool_client.this.client_secret
  sensitive   = true
}

output "hosted_ui_domain" {
  description = "Managed-login (Hosted UI) domain prefix."
  value       = aws_cognito_user_pool_domain.this.domain
}
