variable "name_prefix" {
  description = "Prefix applied to every secret name."
  type        = string
}

variable "recovery_window_in_days" {
  description = "Recovery window before a deleted secret is permanently removed."
  type        = number
}

variable "cognito_client_secret" {
  description = "Cognito app client secret value (generated by Cognito, wired in from the cognito module)."
  type        = string
  sensitive   = true
}

variable "stripe_secret_key" {
  description = "Stripe secret API key. Empty creates the container only; the version is set out of band."
  type        = string
  default     = ""
  sensitive   = true
}

variable "stripe_webhook_secret" {
  description = "Stripe webhook signing secret. Empty creates the container only; the version is set out of band."
  type        = string
  default     = ""
  sensitive   = true
}
